import { withUt } from "uploadthing/tw";

export default withUt({
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["ui-sans-serif", "system-ui", "sans-serif"], // Default system fonts
        jost: ["Jost", "ui-sans-serif", "system-ui", "sans-serif"],
        inter: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "noto-serif-display": ["Noto Serif Display", "ui-serif", "serif"],
      },
      colors: {
        /* Brand scales: values live in globals.css; we only reference them here */
        "brand-primary": {
          50: "rgb(var(--brand-primary-50))",
          100: "rgb(var(--brand-primary-100))",
          200: "rgb(var(--brand-primary-200))",
          300: "rgb(var(--brand-primary-300))",
          400: "rgb(var(--brand-primary-400))",
          500: "rgb(var(--brand-primary-500))",
          600: "rgb(var(--brand-primary-600))",
          700: "rgb(var(--brand-primary-700))",
          800: "rgb(var(--brand-primary-800))",
          900: "rgb(var(--brand-primary-900))",
          950: "rgb(var(--brand-primary-950))",
        },
        "brand-secondary": {
          50: "rgb(var(--brand-secondary-50))",
          100: "rgb(var(--brand-secondary-100))",
          200: "rgb(var(--brand-secondary-200))",
          300: "rgb(var(--brand-secondary-300))",
          400: "rgb(var(--brand-secondary-400))",
          500: "rgb(var(--brand-secondary-500))",
          600: "rgb(var(--brand-secondary-600))",
          700: "rgb(var(--brand-secondary-700))",
          800: "rgb(var(--brand-secondary-800))",
          900: "rgb(var(--brand-secondary-900))",
          950: "rgb(var(--brand-secondary-950))",
        },
        "brand-tertiary": {
          50: "rgb(var(--brand-tertiary-50))",
          100: "rgb(var(--brand-tertiary-100))",
          200: "rgb(var(--brand-tertiary-200))",
          300: "rgb(var(--brand-tertiary-300))",
          400: "rgb(var(--brand-tertiary-400))",
          500: "rgb(var(--brand-tertiary-500))",
          600: "rgb(var(--brand-tertiary-600))",
          700: "rgb(var(--brand-tertiary-700))",
          800: "rgb(var(--brand-tertiary-800))",
          900: "rgb(var(--brand-tertiary-900))",
          950: "rgb(var(--brand-tertiary-950))",
        },
        "brand-success": {
          50: "rgb(var(--brand-success-50))",
          100: "rgb(var(--brand-success-100))",
          200: "rgb(var(--brand-success-200))",
          300: "rgb(var(--brand-success-300))",
          400: "rgb(var(--brand-success-400))",
          500: "rgb(var(--brand-success-500))",
          600: "rgb(var(--brand-success-600))",
          700: "rgb(var(--brand-success-700))",
          800: "rgb(var(--brand-success-800))",
          900: "rgb(var(--brand-success-900))",
          950: "rgb(var(--brand-success-950))",
        },
        "brand-warn": {
          50: "rgb(var(--brand-warn-50))",
          100: "rgb(var(--brand-warn-100))",
          200: "rgb(var(--brand-warn-200))",
          300: "rgb(var(--brand-warn-300))",
          400: "rgb(var(--brand-warn-400))",
          500: "rgb(var(--brand-warn-500))",
          600: "rgb(var(--brand-warn-600))",
          700: "rgb(var(--brand-warn-700))",
          800: "rgb(var(--brand-warn-800))",
          900: "rgb(var(--brand-warn-900))",
          950: "rgb(var(--brand-warn-950))",
        },
        "brand-error": {
          50: "rgb(var(--brand-error-50))",
          100: "rgb(var(--brand-error-100))",
          200: "rgb(var(--brand-error-200))",
          300: "rgb(var(--brand-error-300))",
          400: "rgb(var(--brand-error-400))",
          500: "rgb(var(--brand-error-500))",
          600: "rgb(var(--brand-error-600))",
          700: "rgb(var(--brand-error-700))",
          800: "rgb(var(--brand-error-800))",
          900: "rgb(var(--brand-error-900))",
          950: "rgb(var(--brand-error-950))",
        },
        "brand-light-neutral": {
          50: "rgb(var(--brand-light-neutral-50))",
          100: "rgb(var(--brand-light-neutral-100))",
          200: "rgb(var(--brand-light-neutral-200))",
          300: "rgb(var(--brand-light-neutral-300))",
          400: "rgb(var(--brand-light-neutral-400))",
          500: "rgb(var(--brand-light-neutral-500))",
          600: "rgb(var(--brand-light-neutral-600))",
          700: "rgb(var(--brand-light-neutral-700))",
          800: "rgb(var(--brand-light-neutral-800))",
          900: "rgb(var(--brand-light-neutral-900))",
          950: "rgb(var(--brand-light-neutral-950))",
        },
        "brand-dark-neutral": {
          50: "rgb(var(--brand-dark-neutral-50))",
          100: "rgb(var(--brand-dark-neutral-100))",
          200: "rgb(var(--brand-dark-neutral-200))",
          300: "rgb(var(--brand-dark-neutral-300))",
          400: "rgb(var(--brand-dark-neutral-400))",
          500: "rgb(var(--brand-dark-neutral-500))",
          600: "rgb(var(--brand-dark-neutral-600))",
          700: "rgb(var(--brand-dark-neutral-700))",
          800: "rgb(var(--brand-dark-neutral-800))",
          900: "rgb(var(--brand-dark-neutral-900))",
          950: "rgb(var(--brand-dark-neutral-950))",
        },
        /* Shadcn/semantic tokens — some use HSL (e.g. background), semantic brand use RGB from globals */
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "rgb(var(--primary))",
          foreground: "rgb(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary))",
          foreground: "rgb(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "rgb(var(--accent))",
          foreground: "rgb(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in-right": {
          "0%": {
            opacity: "0",
            transform: "translateX(50px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateX(0)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-right": "slide-in-right 2.5s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
});
